CREATE DATABASE techshop;

USE liveshop;

CREATE TABLE orders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  items TEXT NOT NULL,
  total DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
